### ISSUE TITLE
Rotating Saves: Delete the new loadmeta file also when deleting the old saves

### ISSUE THREAD

**Issue by JebsSY** [linuxgurugamer/AutomatedScreenshots#5]
Earlier a KSP-savegame was only a .SFS file. Now a KSP-savegame is a .SFS file + a .loadmeta file. Automated screenshots saves regulary and creates both files that way. For example: "rotate-123.loadmeta" + "rotate-123.sfs".

However AS only deletes the SFS so the hundreds of loadmeta's stay in the folder. The fix is hopefully easy: The delete function of automated screenshots should delete both files "rotate-123.loadmeta" + "rotate-123.sfs". 

o/ :)

**Comment by linuxgurugamer** [comment]
This was fixed back in version 0.7.9
