### ISSUE TITLE
Icons not found in Linux install

### ISSUE THREAD

**Issue by rkunze** [linuxgurugamer/AutomatedScreenshots#7]
AutomatedScreenshots on Linux shows a blank white square in the toolbar icon instead of the expected image.

KSP.log has a corresponding error entry:
```
ERR 21:25:41.257] ToolbarControl: Cannot find texture to load:AutomatedScreenshots/PluginData/Textures/Auto-38
```
Root cause is an inconsistency in file/directory names: Textures are searched for in `AutomatedScreenshots`, but the actual directory name is `GameData/AutomatedScreenShots`. This does not matter on Windows with its case-insensitive file system, but _is_ an issue with any case-sensitive file system.

I can provide a PR that renames `AutomatedScreenShots` to `AutomatedScreenshots` wherever it is used in the mod, but I can't test that PR myself because I can't build the mod on Linux (the build files seem to be Windows specific with embedded Windows CLI commands, and use tools such as `texttransform.exe` which looks to be specific to Visual Studio).

**Comment by rkunze** [comment]
Workaround: Copy the textures from `GameData/AutomatedScreenShots/PluginData/Textures/`to `GameData/AutomatedScreenshots/PluginData/Textures/`. Make sure to only copy the textures directory to avoid problems with duplicated DLL files.

**Comment by linuxgurugamer** [comment]
Easy fix, I'll get it out today.  Interesting that it took 7 years before someone noticed it :-)

**Comment by linuxgurugamer** [comment]
Released
